### ISSUE TITLE
Manufacture / distributors code

### ISSUE THREAD

**Issue by hildogjr** [lab11/eagle#12]
Hi, I am one of the developer of [KiCost](https://github.com/xesscorp/KiCost), a tool in Python to get the prices from the distributors web site originally did to KiCad, but I expand to CSV BoMs.
I saw that you library already have some web site distributors codes and want to check the compatibility, we use the format `distributor+'#'` (e.g. `mouser#`, `digikey#`, ...) and generic `manf#` for manufacture number.
Cold you attach here some CSV BoM lists to my tests?

**Comment by ppannuto** [comment]
Sure, here's a bunch:

https://github.com/lab11/PlugWatch/blob/master/powerwatch/electron_rev_2/hardware/plugwatch_bom.csv

https://github.com/lab11/permamote/blob/master/hardware/permamote/rev_a/permamote_bom.csv

https://github.com/lab11/slocalization/blob/master/pcb/slotag/slotag_v0p1/slotag_v0p1.csv

https://github.com/lab11/hail/blob/master/hardware/hail/rev_a/hail_bom.csv
https://github.com/lab11/hail/blob/master/hardware/hail/rev_b/hail_bom.csv
https://github.com/lab11/hail/blob/master/hardware/hail/rev_c/hail_bom.csv

https://github.com/lab11/signpost/blob/master/hardware/backplane/rev_c/backplane_bom.csv
https://github.com/lab11/signpost/blob/master/hardware/backplane/rev_d/backplane_bom.csv

https://github.com/lab11/signpost/blob/master/hardware/radio_module/rev_a/radio_module_bom.csv
https://github.com/lab11/signpost/blob/master/hardware/radio_module/rev_b/radio_module_bom.csv

https://github.com/lab11/signpost/blob/master/hardware/power_supply_module/rev_d/power_supply_module_bom.csv

https://github.com/lab11/signpost/blob/master/hardware/debug_backplane/rev_a/debug_backplane_bom.csv
https://github.com/lab11/signpost/blob/master/hardware/debug_backplane/rev_b/debug_backplane_bom.csv
https://github.com/lab11/signpost/blob/master/hardware/debug_backplane/rev_c/debug_backplane_bom.csv

https://github.com/lab11/signpost/blob/master/hardware/controller/rev_a/controller_bom.csv
https://github.com/lab11/signpost/blob/master/hardware/controller/rev_b/controller_bom.csv
https://github.com/lab11/signpost/blob/master/hardware/controller/rev_c/controller_bom.csv
https://github.com/lab11/signpost/blob/master/hardware/controller/rev_d/controller_bom.csv

https://github.com/lab11/signpost/blob/master/hardware/battery_pack/rev_a/battery_pack_bom.csv

**Comment by hildogjr** [comment]
Thanks @ppannuto, this provide some tests and I improved the KiCost tool to read CSVs.
I still have some issue with Mouser that will be fixed soon. File `backplane_bom.csv` and `power_supply_module_bom.csv` have some unexpected behavior already being track (issue 171 of KiCost).

To yours BoM work fine I had to delete the initial header (starting the file in the data header) and add '#' at the end of each distributor name (column code), after I run `kicost -i %file% --exclude mouser`.

[test.zip](https://github.com/lab11/eagle/files/1692179/test.zip)

**Comment by hildogjr** [comment]
Thanks @ppannuto, this provide some tests and I improved the KiCost tool to read CSVs.
I still have some issue if Mouser that will be fixed soon. `backplane_bom.csv` and `power_supply_module_bom.csv` have some unexpected behavior already being track (issue 171 of KiCost).

To yours BoM work fine I had to delete the initial header (starting the file in the data header) and add '#' at the end of each distributor name (column code), after I run `kicost -i %file% --exclude mouser`.

[test.zip](https://github.com/lab11/eagle/files/1692179/test.zip)

**Comment by hildogjr** [comment]
I am closing this issue, but still working the the files that KiCost could not deal with. Check on "test.zip" the results and, if you have any contribution, fell free to open a issue.

**Comment by hildogjr** [comment]
I am closing this issue, but still working the the files that KiCost could not deal with. Check on "test.zip" the results and, if you have any contribution, fell free to open a issue.

**Comment by hildogjr** [comment]
Working with all your files.
[test.zip](https://github.com/lab11/eagle/files/1753921/test.zip)
